// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbsbiqoicypiaioqeswi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRic2JpcW9pY3lwaWFpb3Flc3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzUzNTIsImV4cCI6MjA3NDMxMTM1Mn0.nnpkdBiUiB66TcHoy423jtmSFU-Aihb2WyT2hhodKS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});