// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://zupygwgwsrcwhkwhuwtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1cHlnd2d3c3Jjd2hrd2h1d3RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMjY2MDQsImV4cCI6MjA3OTkwMjYwNH0.UEyLE-HjlFQ-G4ogBAtODrt4gudzz62yxk3AEWyvWcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
