// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxqcoqpbbyxoeggxqkzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54cWNvcXBiYnl4b2VnZ3hxa3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NjU3MzUsImV4cCI6MjA3ODQ0MTczNX0.1cFXsH_5sma1zNIGA5ZQYR0nQnkomiDMBXv9tiriRxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});