name: Apply Supabase Migrations

on:
  push:
    branches: [ "main" ]

jobs:
  apply-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo so CI can access migration files
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: supabase/setup-cli@v1

      - name: Authenticate Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link to Supabase Project
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: supabase link --project-ref "$SUPABASE_PROJECT_ID"

      - name: Apply Migrations
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: supabase db push --password "$SUPABASE_DB_PASSWORD"
